apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::664560360605:role/UdacityFlaskDeployCBKubectlRole
      username: build 
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::664560360605:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-7J8VMCHV66FN
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-28T15:27:40Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1114"
  uid: b5d701a0-3f6e-44a5-a44c-9e1e14cfa83d
